package com.paulgougassian.db.dao.wrapper;

import com.paulgougassian.db.dao.wrapper.functions.PreparedStatementConsumer;
import com.paulgougassian.db.dao.wrapper.functions.PreparedStatementFunction;

public interface PreparedStatementWrapper {
    <T> T executeQuery(String sql, PreparedStatementFunction<? extends T> function);

    <T> T executeQuery(String sql, int autoGeneratedKeys,
                       PreparedStatementFunction<? extends T> function);

    void executeUpdate(String sql, PreparedStatementConsumer consumer);
}
